apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-chatbot
  labels:
    app: flask-chatbot
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flask-chatbot
  template:
    metadata:
      labels:
        app: flask-chatbot
    spec:
    containers:
      - name: flask-chatbot
        image: afyildiz/flask_chatbot:latest
        ports:
        - containerPort: 8000
        env:
        - name: COHERE_API_KEY
          valueFrom:
            secretKeyRef:
              name: cohere-api-secret
              key: COHERE_API_KEY
