name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v2
      with:
        context: .
        tags: ${{ secrets.DOCKER_USERNAME }}/flask-chatbot:latest
        push: true

  deploy:
    name: Deploy to Kubernetes
    needs: build-and-push  # Deploy işlemi, build-and-push işinden sonra başlar
    runs-on: ubuntu-latest

    steps:
    - name: Use kubeconfig from repo
      run: |
        export KUBECONFIG=$(pwd)/k8s/kubeconfig
        kubectl get nodes

    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f ./k8s/secret.yaml
        kubectl apply -f ./k8s/deployment.yaml
        kubectl apply -f ./k8s/service.yaml
