name: CI Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      env:
        COHERE_API_KEY: ${{ secrets.COHERE_API_KEY }}
      run: PYTHONPATH=. pytest

    - name: Set up Kubernetes context
      run: |
        echo "${{ secrets.KUBECONFIG_CONTENT }}" | base64 --decode > kubeconfig
        export KUBECONFIG=$(pwd)/kubeconfig

    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f ./k8s/secret.yaml
        kubectl apply -f ./k8s/deployment.yaml
        kubectl apply -f ./k8s/service.yaml
