name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v2
      with:
        context: .
        tags: ${{ secrets.DOCKER_USERNAME }}/flask-app:latest

  deploy:
    name: Deploy to Kubernetes
    needs: build-and-push  # Deploy işlemi, build-and-push işinden sonra başlar
    runs-on: ubuntu-latest

    steps:
    - name: Set up Kubernetes context
      run: |
        echo "${{ secrets.KUBECONFIG_CONTENT }}" | base64 --decode > kubeconfig
        export KUBECONFIG=$(pwd)/kubeconfig

    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f ./k8s/secret.yaml
        kubectl apply -f ./k8s/deployment.yaml
        kubectl apply -f ./k8s/service.yaml
